import type { Airport } from "../../../data/classes/flights";

export const airports: Airport[] = [
  {
    airportName: "Vancouver International Airport",
    icaoCode: "CYVR",
    iataCode: "YVR",
    lat: "49.1950",
    lon: "-123.1790",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "CA-BC",
    airportType: "large_airport",
    id: 1,
  },
  {
    airportName: "Toronto Pearson International Airport",
    icaoCode: "CYYZ",
    iataCode: "YYZ",
    lat: "43.6777",
    lon: "-79.6248",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "CA-ON",
    airportType: "large_airport",
    id: 2,
  },
  {
    airportName: "John F. Kennedy International Airport",
    icaoCode: "KJFK",
    iataCode: "JFK",
    lat: "40.6413",
    lon: "-73.7781",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "US-NY",
    airportType: "large_airport",
    id: 3,
  },
  {
    airportName: "London Heathrow Airport",
    icaoCode: "EGLL",
    iataCode: "LHR",
    lat: "51.4700",
    lon: "-0.4543",
    continent: "EU",
    isoCountry: "GB",
    isoRegion: "GB-ENG",
    airportType: "large_airport",
    id: 4,
  },
  {
    airportName: "Sydney Kingsford Smith Airport",
    icaoCode: "YSSY",
    iataCode: "SYD",
    lat: "-33.9399",
    lon: "151.1753",
    continent: "OC",
    isoCountry: "AU",
    isoRegion: "AU-NSW",
    airportType: "large_airport",
    id: 5,
  },
  {
    airportName: "Tokyo Haneda Airport",
    icaoCode: "RJTT",
    iataCode: "HND",
    lat: "35.5494",
    lon: "139.7798",
    continent: "AS",
    isoCountry: "JP",
    isoRegion: "JP-13",
    airportType: "large_airport",
    id: 6,
  },
  {
    airportName: "Winnipeg James Armstrong Richardson International Airport",
    icaoCode: "CYWG",
    iataCode: "YWG",
    lat: "49.9097",
    lon: "-97.2399",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "CA-MB",
    airportType: "large_airport",
    id: 7,
  },
  {
    airportName: "Mexico City International Airport",
    icaoCode: "MMMX",
    iataCode: "MEX",
    lat: "19.4361",
    lon: "-99.0719",
    continent: "NA",
    isoCountry: "MX",
    isoRegion: "MX-CMX",
    airportType: "large_airport",
    id: 8,
  },
  {
    airportName: "Istanbul Airport",
    icaoCode: "LTFM",
    iataCode: "IST",
    lat: "41.2753",
    lon: "28.7519",
    continent: "EU",
    isoCountry: "TR",
    isoRegion: "TR-34",
    airportType: "large_airport",
    id: 9,
  },
  {
    airportName: "Los Angeles International Airport",
    icaoCode: "KLAX",
    iataCode: "LAX",
    lat: "33.9416",
    lon: "-118.4085",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "US-CA",
    airportType: "large_airport",
    id: 10,
  },
  {
    airportName: "Paris Charles de Gaulle Airport",
    icaoCode: "LFPG",
    iataCode: "CDG",
    lat: "49.0097",
    lon: "2.5479",
    continent: "EU",
    isoCountry: "FR",
    isoRegion: "FR-IDF",
    airportType: "large_airport",
    id: 11,
  },
  {
    airportName: "Singapore Changi Airport",
    icaoCode: "WSSS",
    iataCode: "SIN",
    lat: "1.3644",
    lon: "103.9915",
    continent: "AS",
    isoCountry: "SG",
    isoRegion: "SG-01",
    airportType: "large_airport",
    id: 12,
  },
  {
    airportName: "Dubai International Airport",
    icaoCode: "OMDB",
    iataCode: "DXB",
    lat: "25.2532",
    lon: "55.3657",
    continent: "AS",
    isoCountry: "AE",
    isoRegion: "AE-DU",
    airportType: "large_airport",
    id: 13,
  },
  {
    airportName: "Sheremetyevo International Airport",
    icaoCode: "UUEE",
    iataCode: "SVO",
    lat: "55.9726",
    lon: "37.4146",
    continent: "EU",
    isoCountry: "RU",
    isoRegion: "RU-MOW",
    airportType: "large_airport",
    id: 14,
  },
  {
    airportName: "Beijing Capital International Airport",
    icaoCode: "ZBAA",
    iataCode: "PEK",
    lat: "40.0801",
    lon: "116.5846",
    continent: "AS",
    isoCountry: "CN",
    isoRegion: "CN-BJ",
    airportType: "large_airport",
    id: 15,
  },
  {
    airportName: "Sao Paulo/Guarulhos International Airport",
    icaoCode: "SBGR",
    iataCode: "GRU",
    lat: "-23.4356",
    lon: "-46.4731",
    continent: "SA",
    isoCountry: "BR",
    isoRegion: "BR-SP",
    airportType: "large_airport",
    id: 16,
  },
  {
    airportName: "Miami International Airport",
    icaoCode: "KMIA",
    iataCode: "MIA",
    lat: "25.7959",
    lon: "-80.2870",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "US-FL",
    airportType: "large_airport",
    id: 17,
  },
  {
    airportName: "Hong Kong International Airport",
    icaoCode: "VHHH",
    iataCode: "HKG",
    lat: "22.3080",
    lon: "113.9185",
    continent: "AS",
    isoCountry: "HK",
    isoRegion: "HK-NT",
    airportType: "large_airport",
    id: 18,
  },
  {
    airportName: "Suvarnabhumi Airport",
    icaoCode: "VTBS",
    iataCode: "BKK",
    lat: "13.6900",
    lon: "100.7501",
    continent: "AS",
    isoCountry: "TH",
    isoRegion: "TH-10",
    airportType: "large_airport",
    id: 19,
  },
  {
    airportName: "Cairo International Airport",
    icaoCode: "HECA",
    iataCode: "CAI",
    lat: "30.1219",
    lon: "31.4056",
    continent: "AF",
    isoCountry: "EG",
    isoRegion: "EG-C",
    airportType: "large_airport",
    id: 20,
  },
  {
    airportName: "Incheon International Airport",
    icaoCode: "RKSI",
    iataCode: "ICN",
    lat: "37.4602",
    lon: "126.4407",
    continent: "AS",
    isoCountry: "KR",
    isoRegion: "KR-41",
    airportType: "large_airport",
    id: 21,
  },
  {
    airportName: "Ninoy Aquino International Airport",
    icaoCode: "RPLL",
    iataCode: "MNL",
    lat: "14.5086",
    lon: "121.0198",
    continent: "AS",
    isoCountry: "PH",
    isoRegion: "PH-00",
    airportType: "large_airport",
    id: 22,
  },
  {
    airportName: "Amsterdam Airport Schiphol",
    icaoCode: "EHAM",
    iataCode: "AMS",
    lat: "52.3105",
    lon: "4.7683",
    continent: "EU",
    isoCountry: "NL",
    isoRegion: "NL-NH",
    airportType: "large_airport",
    id: 23,
  },
  {
    airportName: "Frankfurt Airport",
    icaoCode: "EDDF",
    iataCode: "FRA",
    lat: "50.0379",
    lon: "8.5622",
    continent: "EU",
    isoCountry: "DE",
    isoRegion: "DE-HE",
    airportType: "large_airport",
    id: 24,
  },
  {
    airportName: "Taiwan Taoyuan International Airport",
    icaoCode: "RCTP",
    iataCode: "TPE",
    lat: "25.0797",
    lon: "121.2340",
    continent: "AS",
    isoCountry: "TW",
    isoRegion: "TW-TAO",
    airportType: "large_airport",
    id: 25,
  },
];
