import type { Flight } from "../../../data/classes/flights";
import { airports } from "./airports";

// Helper to find airport by IATA code
const findAirport = (iataCode: string) => {
  const airport = airports.find((a) => a.iataCode === iataCode);
  if (!airport) throw new Error(`Airport not found: ${iataCode}`);
  return airport;
};

export const flights: Flight[] = [
  // Vancouver to Toronto
  {
    id: 1,
    flightNumber: "AC301",
    airline: "AC",
    departureAirport: "YVR",
    arrivalAirport: "YYZ",
    originAirport: findAirport("YVR"),
    destinationAirport: findAirport("YYZ"),
    originAirportId: findAirport("YVR").id,
    destinationAirportId: findAirport("YYZ").id,
    userId: 0,
    user: {} as any,
  },
  // New York to London
  {
    id: 2,
    flightNumber: "BA112",
    airline: "BA",
    departureAirport: "JFK",
    arrivalAirport: "LHR",
    originAirport: findAirport("JFK"),
    destinationAirport: findAirport("LHR"),
    originAirportId: findAirport("JFK").id,
    destinationAirportId: findAirport("LHR").id,
    userId: 0,
    user: {} as any,
  },
  // Sydney to Tokyo
  {
    id: 3,
    flightNumber: "QF25",
    airline: "QF",
    departureAirport: "SYD",
    arrivalAirport: "HND",
    originAirport: findAirport("SYD"),
    destinationAirport: findAirport("HND"),
    originAirportId: findAirport("SYD").id,
    destinationAirportId: findAirport("HND").id,
    userId: 0,
    user: {} as any,
  },
  // Winnipeg to Mexico City
  {
    id: 4,
    flightNumber: "AM692",
    airline: "AM",
    departureAirport: "YWG",
    arrivalAirport: "MEX",
    originAirport: findAirport("YWG"),
    destinationAirport: findAirport("MEX"),
    originAirportId: findAirport("YWG").id,
    destinationAirportId: findAirport("MEX").id,
    userId: 0,
    user: {} as any,
  },
  // Vancouver to Istanbul
  {
    id: 5,
    flightNumber: "TK16",
    airline: "TK",
    departureAirport: "YVR",
    arrivalAirport: "IST",
    originAirport: findAirport("YVR"),
    destinationAirport: findAirport("IST"),
    originAirportId: findAirport("YVR").id,
    destinationAirportId: findAirport("IST").id,
    userId: 0,
    user: {} as any,
  },
  // Los Angeles to Paris
  {
    id: 6,
    flightNumber: "AF68",
    airline: "AF",
    departureAirport: "LAX",
    arrivalAirport: "CDG",
    originAirport: findAirport("LAX"),
    destinationAirport: findAirport("CDG"),
    originAirportId: findAirport("LAX").id,
    destinationAirportId: findAirport("CDG").id,
    userId: 0,
    user: {} as any,
  },
  // Tokyo to Singapore
  {
    id: 7,
    flightNumber: "SQ634",
    airline: "SQ",
    departureAirport: "HND",
    arrivalAirport: "SIN",
    originAirport: findAirport("HND"),
    destinationAirport: findAirport("SIN"),
    originAirportId: findAirport("HND").id,
    destinationAirportId: findAirport("SIN").id,
    userId: 0,
    user: {} as any,
  },
  // Dubai to London
  {
    id: 8,
    flightNumber: "EK1",
    airline: "EK",
    departureAirport: "DXB",
    arrivalAirport: "LHR",
    originAirport: findAirport("DXB"),
    destinationAirport: findAirport("LHR"),
    originAirportId: findAirport("DXB").id,
    destinationAirportId: findAirport("LHR").id,
    userId: 0,
    user: {} as any,
  },
  // Moscow to Beijing
  {
    id: 9,
    flightNumber: "SU574",
    airline: "SU",
    departureAirport: "SVO",
    arrivalAirport: "PEK",
    originAirport: findAirport("SVO"),
    destinationAirport: findAirport("PEK"),
    originAirportId: findAirport("SVO").id,
    destinationAirportId: findAirport("PEK").id,
    userId: 0,
    user: {} as any,
  },
  // São Paulo to Miami
  {
    id: 10,
    flightNumber: "AA963",
    airline: "AA",
    departureAirport: "GRU",
    arrivalAirport: "MIA",
    originAirport: findAirport("GRU"),
    destinationAirport: findAirport("MIA"),
    originAirportId: findAirport("GRU").id,
    destinationAirportId: findAirport("MIA").id,
    userId: 0,
    user: {} as any,
  },
  // Hong Kong to Bangkok
  {
    id: 11,
    flightNumber: "CX701",
    airline: "CX",
    departureAirport: "HKG",
    arrivalAirport: "BKK",
    originAirport: findAirport("HKG"),
    destinationAirport: findAirport("BKK"),
    originAirportId: findAirport("HKG").id,
    destinationAirportId: findAirport("BKK").id,
    userId: 0,
    user: {} as any,
  },
  // Istanbul to Cairo
  {
    id: 12,
    flightNumber: "TK690",
    airline: "TK",
    departureAirport: "IST",
    arrivalAirport: "CAI",
    originAirport: findAirport("IST"),
    destinationAirport: findAirport("CAI"),
    originAirportId: findAirport("IST").id,
    destinationAirportId: findAirport("CAI").id,
    userId: 0,
    user: {} as any,
  },
  // Seoul to Manila
  {
    id: 13,
    flightNumber: "KE621",
    airline: "KE",
    departureAirport: "ICN",
    arrivalAirport: "MNL",
    originAirport: findAirport("ICN"),
    destinationAirport: findAirport("MNL"),
    originAirportId: findAirport("ICN").id,
    destinationAirportId: findAirport("MNL").id,
    userId: 0,
    user: {} as any,
  },
  // Miami to Vancouver
  {
    id: 14,
    flightNumber: "AC1597",
    airline: "AC",
    departureAirport: "MIA",
    arrivalAirport: "YVR",
    originAirport: findAirport("MIA"),
    destinationAirport: findAirport("YVR"),
    originAirportId: findAirport("MIA").id,
    destinationAirportId: findAirport("YVR").id,
    userId: 0,
    user: {} as any,
  },
  // Toronto to New York
  {
    id: 15,
    flightNumber: "AC7402",
    airline: "AC",
    departureAirport: "YYZ",
    arrivalAirport: "JFK",
    originAirport: findAirport("YYZ"),
    destinationAirport: findAirport("JFK"),
    originAirportId: findAirport("YYZ").id,
    destinationAirportId: findAirport("JFK").id,
    userId: 0,
    user: {} as any,
  },
  // Winnipeg to Vancouver
  {
    id: 16,
    flightNumber: "WS185",
    airline: "WS",
    departureAirport: "YWG",
    arrivalAirport: "YVR",
    originAirport: findAirport("YWG"),
    destinationAirport: findAirport("YVR"),
    originAirportId: findAirport("YWG").id,
    destinationAirportId: findAirport("YVR").id,
    userId: 0,
    user: {} as any,
  },
  // Mexico City to Sao Paulo
  {
    id: 17,
    flightNumber: "AM96",
    airline: "AM",
    departureAirport: "MEX",
    arrivalAirport: "GRU",
    originAirport: findAirport("MEX"),
    destinationAirport: findAirport("GRU"),
    originAirportId: findAirport("MEX").id,
    destinationAirportId: findAirport("GRU").id,
    userId: 0,
    user: {} as any,
  },
  // Vancouver to Amsterdam
  {
    id: 18,
    flightNumber: "KL682",
    airline: "KL",
    departureAirport: "YVR",
    arrivalAirport: "AMS",
    originAirport: findAirport("YVR"),
    destinationAirport: findAirport("AMS"),
    originAirportId: findAirport("YVR").id,
    destinationAirportId: findAirport("AMS").id,
    userId: 0,
    user: {} as any,
  },
  // Amsterdam to Moscow
  {
    id: 19,
    flightNumber: "SU2504",
    airline: "SU",
    departureAirport: "AMS",
    arrivalAirport: "SVO",
    originAirport: findAirport("AMS"),
    destinationAirport: findAirport("SVO"),
    originAirportId: findAirport("AMS").id,
    destinationAirportId: findAirport("SVO").id,
    userId: 0,
    user: {} as any,
  },
  // Beijing to Frankfurt
  {
    id: 20,
    flightNumber: "LH720",
    airline: "LH",
    departureAirport: "PEK",
    arrivalAirport: "FRA",
    originAirport: findAirport("PEK"),
    destinationAirport: findAirport("FRA"),
    originAirportId: findAirport("PEK").id,
    destinationAirportId: findAirport("FRA").id,
    userId: 0,
    user: {} as any,
  },
  // Paris to Cairo
  {
    id: 21,
    flightNumber: "AF638",
    airline: "AF",
    departureAirport: "CDG",
    arrivalAirport: "CAI",
    originAirport: findAirport("CDG"),
    destinationAirport: findAirport("CAI"),
    originAirportId: findAirport("CDG").id,
    destinationAirportId: findAirport("CAI").id,
    userId: 0,
    user: {} as any,
  },
  // Vancouver to Frankfurt
  {
    id: 22,
    flightNumber: "AC873",
    airline: "AC",
    departureAirport: "YVR",
    arrivalAirport: "FRA",
    originAirport: findAirport("YVR"),
    destinationAirport: findAirport("FRA"),
    originAirportId: findAirport("YVR").id,
    destinationAirportId: findAirport("FRA").id,
    userId: 0,
    user: {} as any,
  },
  // Tokyo to Seoul
  {
    id: 23,
    flightNumber: "NH861",
    airline: "NH",
    departureAirport: "HND",
    arrivalAirport: "ICN",
    originAirport: findAirport("HND"),
    destinationAirport: findAirport("ICN"),
    originAirportId: findAirport("HND").id,
    destinationAirportId: findAirport("ICN").id,
    userId: 0,
    user: {} as any,
  },
  // Hong Kong to Taipei
  {
    id: 24,
    flightNumber: "CX470",
    airline: "CX",
    departureAirport: "HKG",
    arrivalAirport: "TPE",
    originAirport: findAirport("HKG"),
    destinationAirport: findAirport("TPE"),
    originAirportId: findAirport("HKG").id,
    destinationAirportId: findAirport("TPE").id,
    userId: 0,
    user: {} as any,
  },
  // Taipei to Manila
  {
    id: 25,
    flightNumber: "BR271",
    airline: "BR",
    departureAirport: "TPE",
    arrivalAirport: "MNL",
    originAirport: findAirport("TPE"),
    destinationAirport: findAirport("MNL"),
    originAirportId: findAirport("TPE").id,
    destinationAirportId: findAirport("MNL").id,
    userId: 0,
    user: {} as any,
  },
  // Seoul to Taipei
  {
    id: 26,
    flightNumber: "KE692",
    airline: "KE",
    departureAirport: "ICN",
    arrivalAirport: "TPE",
    originAirport: findAirport("ICN"),
    destinationAirport: findAirport("TPE"),
    originAirportId: findAirport("ICN").id,
    destinationAirportId: findAirport("TPE").id,
    userId: 0,
    user: {} as any,
  },
  // Sydney to Los Angeles
  {
    id: 27,
    flightNumber: "QF11",
    airline: "QF",
    departureAirport: "SYD",
    arrivalAirport: "LAX",
    originAirport: findAirport("SYD"),
    destinationAirport: findAirport("LAX"),
    originAirportId: findAirport("SYD").id,
    destinationAirportId: findAirport("LAX").id,
    userId: 0,
    user: {} as any,
  },
];
