import type { APIAirport } from "./data/classes/flights/Airport";
import type { APIFlight } from "./data/classes/flights/Flight";

const airportDatabase: Record<string, APIAirport> = {
  YVR: {
    id: 1,
    iataCode: "YVR",
    icaoCode: "CYYZ",
    airportName: "Vancouver International Airport",
    lat: "49.1900",
    lon: "-123.1794",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "BC",
    airportType: "large_airport",
  },
  YTZ: {
    id: 2,
    iataCode: "YTZ",
    icaoCode: "CYTZ",
    airportName: "Toronto City Airport",
    lat: "43.6270",
    lon: "-79.3957",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "ON",
    airportType: "medium_airport",
  },
  YOW: {
    id: 3,
    iataCode: "YOW",
    icaoCode: "CYOW",
    airportName: "Ottawa Macdonald-Cartier International Airport",
    lat: "45.3225",
    lon: "-75.6692",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "ON",
    airportType: "large_airport",
  },
  YUL: {
    id: 4,
    iataCode: "YUL",
    icaoCode: "CYUL",
    airportName: "Montréal-Trudeau International Airport",
    lat: "45.4655",
    lon: "-73.7494",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "QC",
    airportType: "large_airport",
  },
  YYJ: {
    id: 5,
    iataCode: "YYJ",
    icaoCode: "CYYJ",
    airportName: "Victoria International Airport",
    lat: "48.6461",
    lon: "-123.4259",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "BC",
    airportType: "medium_airport",
  },
  FRA: {
    id: 6,
    iataCode: "FRA",
    icaoCode: "EDDF",
    airportName: "Frankfurt am Main Airport",
    lat: "50.0379",
    lon: "8.5622",
    continent: "EU",
    isoCountry: "DE",
    isoRegion: "HE",
    airportType: "large_airport",
  },
  BEG: {
    id: 7,
    iataCode: "BEG",
    icaoCode: "LYBE",
    airportName: "Belgrade Nikola Tesla Airport",
    lat: "44.8184",
    lon: "20.2894",
    continent: "EU",
    isoCountry: "RS",
    isoRegion: "00",
    airportType: "large_airport",
  },
  DTM: {
    id: 8,
    iataCode: "DTM",
    icaoCode: "EDDL",
    airportName: "Düsseldorf International Airport",
    lat: "51.2895",
    lon: "6.7661",
    continent: "EU",
    isoCountry: "DE",
    isoRegion: "NW",
    airportType: "large_airport",
  },
  AMS: {
    id: 9,
    iataCode: "AMS",
    icaoCode: "EHAM",
    airportName: "Amsterdam Airport Schiphol",
    lat: "52.3086",
    lon: "4.7639",
    continent: "EU",
    isoCountry: "NL",
    isoRegion: "NH",
    airportType: "large_airport",
  },
  SEA: {
    id: 10,
    iataCode: "SEA",
    icaoCode: "KSEA",
    airportName: "Seattle-Tacoma International Airport",
    lat: "47.4502",
    lon: "-122.3088",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "WA",
    airportType: "large_airport",
  },
  FCO: {
    id: 11,
    iataCode: "FCO",
    icaoCode: "LIRF",
    airportName: "Leonardo da Vinci–Fiumicino Airport",
    lat: "41.8002",
    lon: "12.2388",
    continent: "EU",
    isoCountry: "IT",
    isoRegion: "RM",
    airportType: "large_airport",
  },
  CGN: {
    id: 12,
    iataCode: "CGN",
    icaoCode: "EDDF",
    airportName: "Cologne Bonn Airport",
    lat: "50.8679",
    lon: "6.8855",
    continent: "EU",
    isoCountry: "DE",
    isoRegion: "NW",
    airportType: "large_airport",
  },
  SLC: {
    id: 13,
    iataCode: "SLC",
    icaoCode: "KSLC",
    airportName: "Salt Lake City International Airport",
    lat: "40.7884",
    lon: "-111.8787",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "UT",
    airportType: "large_airport",
  },
  YYC: {
    id: 14,
    iataCode: "YYC",
    icaoCode: "CYYZ",
    airportName: "Calgary International Airport",
    lat: "51.1214",
    lon: "-114.0055",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "AB",
    airportType: "large_airport",
  },
  CXH: {
    id: 15,
    iataCode: "CXH",
    icaoCode: "CXHH",
    airportName: "Cormorant Island Airport",
    lat: "50.1500",
    lon: "-124.7167",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "BC",
    airportType: "small_airport",
  },
  ZNA: {
    id: 16,
    iataCode: "ZNA",
    icaoCode: "CZNA",
    airportName: "Nanaimo Airport",
    lat: "49.0504",
    lon: "-123.8760",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "BC",
    airportType: "medium_airport",
  },
  TRD: {
    id: 17,
    iataCode: "TRD",
    icaoCode: "ENVA",
    airportName: "Trondheim Airport",
    lat: "63.4569",
    lon: "10.9241",
    continent: "EU",
    isoCountry: "NO",
    isoRegion: "50",
    airportType: "large_airport",
  },
  YYZ: {
    id: 18,
    iataCode: "YYZ",
    icaoCode: "CYYZ",
    airportName: "Toronto Pearson International Airport",
    lat: "43.6777",
    lon: "-79.6248",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "ON",
    airportType: "large_airport",
  },
  YEG: {
    id: 19,
    iataCode: "YEG",
    icaoCode: "CYEG",
    airportName: "Edmonton International Airport",
    lat: "53.3097",
    lon: "-113.5800",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "AB",
    airportType: "large_airport",
  },
  LGW: {
    id: 20,
    iataCode: "LGW",
    icaoCode: "EGKK",
    airportName: "London Gatwick Airport",
    lat: "51.1537",
    lon: "-0.1821",
    continent: "EU",
    isoCountry: "GB",
    isoRegion: "ENG",
    airportType: "large_airport",
  },
  HEL: {
    id: 21,
    iataCode: "HEL",
    icaoCode: "EFHK",
    airportName: "Helsinki Airport",
    lat: "60.3172",
    lon: "25.2458",
    continent: "EU",
    isoCountry: "FI",
    isoRegion: "17",
    airportType: "large_airport",
  },
  STN: {
    id: 22,
    iataCode: "STN",
    icaoCode: "EGSS",
    airportName: "London Stansted Airport",
    lat: "51.8947",
    lon: "0.2375",
    continent: "EU",
    isoCountry: "GB",
    isoRegion: "ENG",
    airportType: "large_airport",
  },
  ARN: {
    id: 23,
    iataCode: "ARN",
    icaoCode: "ESSA",
    airportName: "Stockholm Arlanda Airport",
    lat: "59.6519",
    lon: "17.9289",
    continent: "EU",
    isoCountry: "SE",
    isoRegion: "AB",
    airportType: "large_airport",
  },
  OSL: {
    id: 24,
    iataCode: "OSL",
    icaoCode: "ENGM",
    airportName: "Oslo Airport",
    lat: "60.2041",
    lon: "11.0841",
    continent: "EU",
    isoCountry: "NO",
    isoRegion: "02",
    airportType: "large_airport",
  },
  ORD: {
    id: 25,
    iataCode: "ORD",
    icaoCode: "KORD",
    airportName: "Chicago O'Hare International Airport",
    lat: "41.9742",
    lon: "-87.9073",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "IL",
    airportType: "large_airport",
  },
  YHZ: {
    id: 26,
    iataCode: "YHZ",
    icaoCode: "CYHZ",
    airportName: "Halifax Stanfield International Airport",
    lat: "44.8844",
    lon: "-63.5058",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "NS",
    airportType: "large_airport",
  },
  SFO: {
    id: 27,
    iataCode: "SFO",
    icaoCode: "KSFO",
    airportName: "San Francisco International Airport",
    lat: "37.6213",
    lon: "-122.3790",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "CA",
    airportType: "large_airport",
  },
  IAH: {
    id: 28,
    iataCode: "IAH",
    icaoCode: "KIAH",
    airportName: "Houston George Bush Intercontinental Airport",
    lat: "29.9844",
    lon: "-95.3437",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "TX",
    airportType: "large_airport",
  },
  SJU: {
    id: 29,
    iataCode: "SJU",
    icaoCode: "TJSJ",
    airportName: "Luis Muñoz Marín International Airport",
    lat: "18.4386",
    lon: "-66.0019",
    continent: "NA",
    isoCountry: "PR",
    isoRegion: "00",
    airportType: "large_airport",
  },
  YQB: {
    id: 30,
    iataCode: "YQB",
    icaoCode: "CYQB",
    airportName: "Quebec City Jean Lesage International Airport",
    lat: "46.8111",
    lon: "-71.2078",
    continent: "NA",
    isoCountry: "CA",
    isoRegion: "QC",
    airportType: "large_airport",
  },
  LHR: {
    id: 31,
    iataCode: "LHR",
    icaoCode: "EGLL",
    airportName: "London Heathrow Airport",
    lat: "51.4700",
    lon: "-0.4543",
    continent: "EU",
    isoCountry: "GB",
    isoRegion: "ENG",
    airportType: "large_airport",
  },
  DUB: {
    id: 32,
    iataCode: "DUB",
    icaoCode: "EIDW",
    airportName: "Dublin Airport",
    lat: "53.4129",
    lon: "-6.2700",
    continent: "EU",
    isoCountry: "IE",
    isoRegion: "D",
    airportType: "large_airport",
  },
  BHX: {
    id: 33,
    iataCode: "BHX",
    icaoCode: "EGBB",
    airportName: "Birmingham Airport",
    lat: "52.4539",
    lon: "-1.7480",
    continent: "EU",
    isoCountry: "GB",
    isoRegion: "ENG",
    airportType: "large_airport",
  },
  EWR: {
    id: 34,
    iataCode: "EWR",
    icaoCode: "KEWR",
    airportName: "Newark Liberty International Airport",
    lat: "40.6895",
    lon: "-74.1745",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "NJ",
    airportType: "large_airport",
  },
  LIM: {
    id: 35,
    iataCode: "LIM",
    icaoCode: "SPIM",
    airportName: "Jorge Chávez International Airport",
    lat: "-12.0219",
    lon: "-77.1144",
    continent: "SA",
    isoCountry: "PE",
    isoRegion: "LIM",
    airportType: "large_airport",
  },
  CUZ: {
    id: 36,
    iataCode: "CUZ",
    icaoCode: "SPZO",
    airportName: "Alejandro Velasco Astete International Airport",
    lat: "-13.5952",
    lon: "-71.9418",
    continent: "SA",
    isoCountry: "PE",
    isoRegion: "CUS",
    airportType: "large_airport",
  },
  PEM: {
    id: 37,
    iataCode: "PEM",
    icaoCode: "CIPEM",
    airportName: "Padre Aldamiz International Airport",
    lat: "-12.6136",
    lon: "-69.2286",
    continent: "SA",
    isoCountry: "PE",
    isoRegion: "AM",
    airportType: "small_airport",
  },
  DUS: {
    id: 38,
    iataCode: "DUS",
    icaoCode: "EDDL",
    airportName: "Düsseldorf International Airport",
    lat: "51.2895",
    lon: "6.7661",
    continent: "EU",
    isoCountry: "DE",
    isoRegion: "NW",
    airportType: "large_airport",
  },
  KOA: {
    id: 39,
    iataCode: "KOA",
    icaoCode: "PHKO",
    airportName: "Kona International Airport",
    lat: "19.7383",
    lon: "-156.0456",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "HI",
    airportType: "large_airport",
  },
  DFW: {
    id: 40,
    iataCode: "DFW",
    icaoCode: "KDFW",
    airportName: "Dallas/Fort Worth International Airport",
    lat: "32.8975",
    lon: "-97.0381",
    continent: "NA",
    isoCountry: "US",
    isoRegion: "TX",
    airportType: "large_airport",
  },
};

const mockFlights: APIFlight[] = [
  {
    id: 1,
    flightNumber: "PD2205",
    airline: "Porter",
    date: new Date("2025-11-16"),
    planeModel: "DHC-8-400 Dash 8Q",
    planeRegistration: "C-GLQE",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YTZ,
    destinationAirport: airportDatabase.YOW,
    departureAirport: "YTZ",
    arrivalAirport: "YOW",
    originAirportId: 2,
    destinationAirportId: 3,
  },
  {
    id: 2,
    flightNumber: "PD263",
    airline: "Porter",
    date: new Date("2025-11-16"),
    planeModel: "Embraer 195 E2",
    planeRegistration: "C-GZQR",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YOW,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YOW",
    arrivalAirport: "YVR",
    originAirportId: 3,
    destinationAirportId: 1,
  },
  {
    id: 3,
    flightNumber: "PD2484",
    airline: "Porter",
    date: new Date("2025-11-11"),
    planeModel: "DHC-8-400 Dash 8Q",
    planeRegistration: "C-GKQB",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YUL,
    destinationAirport: airportDatabase.YTZ,
    departureAirport: "YUL",
    arrivalAirport: "YTZ",
    originAirportId: 4,
    destinationAirportId: 2,
  },
  {
    id: 4,
    flightNumber: "PD372",
    airline: "Porter",
    date: new Date("2025-11-11"),
    planeModel: "Embraer 195 E2",
    planeRegistration: "C-GZQB",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YUL,
    departureAirport: "YVR",
    arrivalAirport: "YUL",
    originAirportId: 1,
    destinationAirportId: 4,
  },
  {
    id: 5,
    flightNumber: "DE2454",
    airline: "Condor",
    date: new Date("2025-07-12"),
    planeModel: "Airbus A330-900neo",
    planeRegistration: "D-ANRE",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.FRA,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "FRA",
    arrivalAirport: "YVR",
    originAirportId: 6,
    destinationAirportId: 1,
  },
  {
    id: 6,
    flightNumber: "W64091",
    airline: "Wizz Air",
    date: new Date("2025-07-01"),
    planeModel: "Airbus A321neo",
    planeRegistration: "9H-WMA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.BEG,
    destinationAirport: airportDatabase.DTM,
    departureAirport: "BEG",
    arrivalAirport: "DTM",
    originAirportId: 7,
    destinationAirportId: 8,
  },
  {
    id: 7,
    flightNumber: "W64092",
    airline: "Wizz Air",
    date: new Date("2025-06-27"),
    planeModel: "Airbus A320",
    planeRegistration: "HA-LWU",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.DTM,
    destinationAirport: airportDatabase.BEG,
    departureAirport: "DTM",
    arrivalAirport: "BEG",
    originAirportId: 8,
    destinationAirportId: 7,
  },
  {
    id: 8,
    flightNumber: "DE2455",
    airline: "Condor",
    date: new Date("2025-06-22"),
    planeModel: "Airbus A330-900neo",
    planeRegistration: "D-ANRH",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.FRA,
    departureAirport: "YVR",
    arrivalAirport: "FRA",
    originAirportId: 1,
    destinationAirportId: 6,
  },
  {
    id: 9,
    flightNumber: "4N521",
    airline: "Air North",
    date: new Date("2025-02-14"),
    planeModel: "Boeing 737-500",
    planeRegistration: "C-FANF",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYJ,
    departureAirport: "YVR",
    arrivalAirport: "YYJ",
    originAirportId: 1,
    destinationAirportId: 5,
  },
  {
    id: 10,
    flightNumber: "DL143",
    airline: "Delta",
    date: new Date("2025-01-08"),
    planeModel: "Airbus A330-900neo",
    planeRegistration: "N428DX",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.SEA,
    departureAirport: "AMS",
    arrivalAirport: "SEA",
    originAirportId: 9,
    destinationAirportId: 10,
  },
  {
    id: 11,
    flightNumber: "DL3893",
    airline: "Delta",
    date: new Date("2025-01-08"),
    planeModel: "Embraer 175 (long wing)",
    planeRegistration: "N276SY",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.SEA,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "SEA",
    arrivalAirport: "YVR",
    originAirportId: 10,
    destinationAirportId: 1,
  },
  {
    id: 12,
    flightNumber: "FR933",
    airline: "Ryanair",
    date: new Date("2025-01-03"),
    planeModel: "Boeing 737 MAX 8",
    planeRegistration: "9H-VVD",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.FCO,
    destinationAirport: airportDatabase.CGN,
    departureAirport: "FCO",
    arrivalAirport: "CGN",
    originAirportId: 11,
    destinationAirportId: 12,
  },
  {
    id: 13,
    flightNumber: "FR932",
    airline: "Ryanair",
    date: new Date("2024-12-31"),
    planeModel: "Boeing 737-800",
    planeRegistration: "9H-QCH",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.CGN,
    destinationAirport: airportDatabase.FCO,
    departureAirport: "CGN",
    arrivalAirport: "FCO",
    originAirportId: 12,
    destinationAirportId: 11,
  },
  {
    id: 14,
    flightNumber: "DL56",
    airline: "Delta",
    date: new Date("2024-12-18"),
    planeModel: "Airbus A330-300",
    planeRegistration: "N825NW",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.SLC,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "SLC",
    arrivalAirport: "AMS",
    originAirportId: 13,
    destinationAirportId: 9,
  },
  {
    id: 15,
    flightNumber: "DL3691",
    airline: "Delta",
    date: new Date("2024-12-18"),
    planeModel: "Embraer 175 (long wing)",
    planeRegistration: "N283SY",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.SLC,
    departureAirport: "YVR",
    arrivalAirport: "SLC",
    originAirportId: 1,
    destinationAirportId: 13,
  },
  {
    id: 16,
    flightNumber: "AC345",
    airline: "Air Canada",
    date: new Date("2024-10-29"),
    planeModel: "Boeing 787-9",
    planeRegistration: "C-FPQB",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YOW,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YOW",
    arrivalAirport: "YVR",
    originAirportId: 3,
    destinationAirportId: 1,
  },
  {
    id: 17,
    flightNumber: "AC356",
    airline: "Air Canada",
    date: new Date("2024-10-26"),
    planeModel: "Airbus A320",
    planeRegistration: "C-FGKH",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYC,
    destinationAirport: airportDatabase.YOW,
    departureAirport: "YYC",
    arrivalAirport: "YOW",
    originAirportId: 14,
    destinationAirportId: 3,
  },
  {
    id: 18,
    flightNumber: "AC204",
    airline: "Air Canada",
    date: new Date("2024-10-26"),
    planeModel: "Airbus A321",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYC,
    departureAirport: "YVR",
    arrivalAirport: "YYC",
    originAirportId: 1,
    destinationAirportId: 14,
  },
  {
    id: 20,
    flightNumber: "KL681",
    airline: "KLM",
    date: new Date("2024-06-16"),
    planeModel: "Boeing 777-300 ER",
    planeRegistration: "PH-BVF",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "AMS",
    arrivalAirport: "YVR",
    originAirportId: 9,
    destinationAirportId: 1,
  },
  {
    id: 21,
    flightNumber: "KL1152",
    airline: "KLM",
    date: new Date("2024-06-09"),
    planeModel: "Embraer 190",
    planeRegistration: "PH-EXV",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.TRD,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "TRD",
    arrivalAirport: "AMS",
    originAirportId: 17,
    destinationAirportId: 9,
  },
  {
    id: 22,
    flightNumber: "KL1153",
    airline: "KLM",
    date: new Date("2024-05-25"),
    planeModel: "Embraer 190",
    planeRegistration: "PH-EZR",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.TRD,
    departureAirport: "AMS",
    arrivalAirport: "TRD",
    originAirportId: 9,
    destinationAirportId: 17,
  },
  {
    id: 23,
    flightNumber: "KL682",
    airline: "KLM",
    date: new Date("2024-05-18"),
    planeModel: "Boeing 777-300 ER",
    planeRegistration: "PH-BVC",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "YVR",
    arrivalAirport: "AMS",
    originAirportId: 1,
    destinationAirportId: 9,
  },
  {
    id: 24,
    flightNumber: "AC125",
    airline: "Air Canada",
    date: new Date("2024-05-12"),
    planeModel: "Boeing 787-9",
    planeRegistration: "C-FRTU",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYZ,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YYZ",
    arrivalAirport: "YVR",
    originAirportId: 18,
    destinationAirportId: 1,
  },
  {
    id: 25,
    flightNumber: "AC100",
    airline: "Air Canada",
    date: new Date("2024-05-06"),
    planeModel: "Airbus A321",
    planeRegistration: "C-FGKN",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYZ,
    departureAirport: "YVR",
    arrivalAirport: "YYZ",
    originAirportId: 1,
    destinationAirportId: 18,
  },
  {
    id: 26,
    flightNumber: "WS171",
    airline: "WestJet",
    date: new Date("2023-11-13"),
    planeModel: "Boeing 737 MAX 8",
    planeRegistration: "C-FXWJ",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YEG,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YEG",
    arrivalAirport: "YVR",
    originAirportId: 19,
    destinationAirportId: 1,
  },
  {
    id: 27,
    flightNumber: "WS162",
    airline: "WestJet",
    date: new Date("2023-11-10"),
    planeModel: "Boeing 737-700",
    planeRegistration: "C-FWSI",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YEG,
    departureAirport: "YVR",
    arrivalAirport: "YEG",
    originAirportId: 1,
    destinationAirportId: 19,
  },
  {
    id: 28,
    flightNumber: "WS119",
    airline: "WestJet",
    date: new Date("2023-05-08"),
    planeModel: "Boeing 737-700",
    planeRegistration: "C-FWSV",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYC,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YYC",
    arrivalAirport: "YVR",
    originAirportId: 14,
    destinationAirportId: 1,
  },
  {
    id: 29,
    flightNumber: "WS2",
    airline: "WestJet",
    date: new Date("2023-05-08"),
    planeModel: "Boeing 787-9",
    planeRegistration: "C-FAJA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.LGW,
    destinationAirport: airportDatabase.YYC,
    departureAirport: "LGW",
    arrivalAirport: "YYC",
    originAirportId: 20,
    destinationAirportId: 14,
  },
  {
    id: 30,
    flightNumber: "FR2345",
    airline: "Ryanair",
    date: new Date("2023-05-04"),
    planeModel: "Boeing 737 MAX 8",
    planeRegistration: "EI-HES",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.HEL,
    destinationAirport: airportDatabase.STN,
    departureAirport: "HEL",
    arrivalAirport: "STN",
    originAirportId: 21,
    destinationAirportId: 22,
  },
  {
    id: 31,
    flightNumber: "SK708",
    airline: "Scandinavian Airlines",
    date: new Date("2023-05-02"),
    planeModel: "Airbus A320neo",
    planeRegistration: "EI-SIC",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.ARN,
    destinationAirport: airportDatabase.HEL,
    departureAirport: "ARN",
    arrivalAirport: "HEL",
    originAirportId: 23,
    destinationAirportId: 21,
  },
  {
    id: 32,
    flightNumber: "RK1392",
    airline: "Ryanair",
    date: new Date("2023-04-27"),
    planeModel: "Boeing 737-800",
    planeRegistration: "G-RUKL",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.STN,
    destinationAirport: airportDatabase.OSL,
    departureAirport: "STN",
    arrivalAirport: "OSL",
    originAirportId: 22,
    destinationAirportId: 24,
  },
  {
    id: 33,
    flightNumber: "TS771",
    airline: "Air Transat",
    date: new Date("2023-04-25"),
    planeModel: "Airbus A321neo",
    planeRegistration: "C-GOIK",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YUL,
    departureAirport: "YVR",
    arrivalAirport: "YUL",
    originAirportId: 1,
    destinationAirportId: 4,
  },
  {
    id: 34,
    flightNumber: "TS728",
    airline: "Air Transat",
    date: new Date("2023-04-25"),
    planeModel: "Airbus A321neo",
    planeRegistration: "C-GOIP",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YUL,
    destinationAirport: airportDatabase.LGW,
    departureAirport: "YUL",
    arrivalAirport: "LGW",
    originAirportId: 4,
    destinationAirportId: 20,
  },
  {
    id: 35,
    flightNumber: "UA1580",
    airline: "Air Canada",
    date: new Date("2023-01-06"),
    planeModel: "Airbus A320",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.ORD,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "ORD",
    arrivalAirport: "YVR",
    originAirportId: 25,
    destinationAirportId: 1,
  },
  {
    id: 36,
    flightNumber: "UA908",
    airline: "Air Canada",
    date: new Date("2023-01-06"),
    planeModel: "Boeing 787-8",
    planeRegistration: "N27901",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.ORD,
    departureAirport: "AMS",
    arrivalAirport: "ORD",
    originAirportId: 9,
    destinationAirportId: 25,
  },
  {
    id: 37,
    flightNumber: "UA1756",
    airline: "United Airlines",
    date: new Date("2022-12-21"),
    planeModel: "Airbus A320",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.ORD,
    departureAirport: "YVR",
    arrivalAirport: "ORD",
    originAirportId: 1,
    destinationAirportId: 25,
  },
  {
    id: 38,
    flightNumber: "UA909",
    airline: "United Airlines",
    date: new Date("2022-12-21"),
    planeModel: "Boeing 777-200 ER",
    planeRegistration: "N797UA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.ORD,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "ORD",
    arrivalAirport: "AMS",
    originAirportId: 25,
    destinationAirportId: 9,
  },
  {
    id: 39,
    flightNumber: "F898",
    airline: "Flair",
    date: new Date("2022-09-03"),
    planeModel: "Boeing 737 MAX 8",
    planeRegistration: "C-FLUT",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YEG,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YEG",
    arrivalAirport: "YVR",
    originAirportId: 19,
    destinationAirportId: 1,
  },
  {
    id: 40,
    flightNumber: "WO265",
    airline: "Swoop",
    date: new Date("2022-09-02"),
    planeModel: "Boeing 737-800",
    planeRegistration: "C-FLBV",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YHZ,
    destinationAirport: airportDatabase.YEG,
    departureAirport: "YHZ",
    arrivalAirport: "YEG",
    originAirportId: 26,
    destinationAirportId: 19,
  },
  {
    id: 41,
    flightNumber: "TS933",
    airline: "Air Transat",
    date: new Date("2022-08-25"),
    planeModel: "Airbus A321",
    planeRegistration: "C-GEZD",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYZ,
    departureAirport: "YVR",
    arrivalAirport: "YYZ",
    originAirportId: 1,
    destinationAirportId: 18,
  },
  {
    id: 42,
    flightNumber: "F8148",
    airline: "Flair",
    date: new Date("2022-08-25"),
    planeModel: "Boeing 737 MAX 8",
    planeRegistration: "C-FLEJ",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYZ,
    destinationAirport: airportDatabase.YHZ,
    departureAirport: "YYZ",
    arrivalAirport: "YHZ",
    originAirportId: 18,
    destinationAirportId: 26,
  },
  {
    id: 43,
    flightNumber: "AC569",
    airline: "Air Canada",
    date: new Date("2022-08-06"),
    planeModel: "Airbus A320",
    planeRegistration: "C-FXCD",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.SFO,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "SFO",
    arrivalAirport: "YVR",
    originAirportId: 27,
    destinationAirportId: 1,
  },
  {
    id: 44,
    flightNumber: "AC568",
    airline: "Air Canada",
    date: new Date("2022-08-03"),
    planeModel: "Airbus A220-300",
    planeRegistration: "C-GJXE",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.SFO,
    departureAirport: "YVR",
    arrivalAirport: "SFO",
    originAirportId: 1,
    destinationAirportId: 27,
  },
  {
    id: 45,
    flightNumber: "UA1973",
    airline: "United Airlines",
    date: new Date("2019-01-16"),
    planeModel: "Boeing 737-800",
    planeRegistration: "N16217",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.IAH,
    destinationAirport: airportDatabase.SFO,
    departureAirport: "IAH",
    arrivalAirport: "SFO",
    originAirportId: 28,
    destinationAirportId: 27,
  },
  {
    id: 46,
    flightNumber: "UA1860",
    airline: "United Airlines",
    date: new Date("2019-01-16"),
    planeModel: "Boeing 737-900 ER",
    planeRegistration: "N53441",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.SJU,
    destinationAirport: airportDatabase.IAH,
    departureAirport: "SJU",
    arrivalAirport: "IAH",
    originAirportId: 29,
    destinationAirportId: 28,
  },
  {
    id: 47,
    flightNumber: "UA1867",
    airline: "United Airlines",
    date: new Date("2019-01-07"),
    planeModel: "Airbus A320",
    planeRegistration: "N404UA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.SEA,
    destinationAirport: airportDatabase.IAH,
    departureAirport: "SEA",
    arrivalAirport: "IAH",
    originAirportId: 10,
    destinationAirportId: 28,
  },
  {
    id: 48,
    flightNumber: "UA1914",
    airline: "United Airlines",
    date: new Date("2019-01-07"),
    planeModel: "Boeing 737-900 ER",
    planeRegistration: "N36444",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.IAH,
    destinationAirport: airportDatabase.SJU,
    departureAirport: "IAH",
    arrivalAirport: "SJU",
    originAirportId: 28,
    destinationAirportId: 29,
  },
  {
    id: 49,
    flightNumber: "TS345",
    airline: "Air Transat",
    date: new Date("2018-09-02"),
    planeModel: "Airbus A330-200",
    planeRegistration: "C-GUBL",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "AMS",
    arrivalAirport: "YVR",
    originAirportId: 9,
    destinationAirportId: 1,
  },
  {
    id: 50,
    flightNumber: "TS350",
    airline: "Air Transat",
    date: new Date("2018-08-13"),
    planeModel: "Airbus A330-200",
    planeRegistration: "C-GTSJ",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYZ,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "YYZ",
    arrivalAirport: "AMS",
    originAirportId: 18,
    destinationAirportId: 9,
  },
  {
    id: 51,
    flightNumber: "TS930",
    airline: "Air Transat",
    date: new Date("2018-08-12"),
    planeModel: "Boeing 737-800",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYZ,
    departureAirport: "YVR",
    arrivalAirport: "YYZ",
    originAirportId: 1,
    destinationAirportId: 18,
  },
  {
    id: 52,
    flightNumber: undefined,
    airline: undefined,
    date: new Date("2018-08-11"),
    planeModel: undefined,
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YQB,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YQB",
    arrivalAirport: "YVR",
    originAirportId: 30,
    destinationAirportId: 1,
  },
  {
    id: 53,
    flightNumber: "AC302",
    airline: "Air Canada",
    date: new Date("2018-06-30"),
    planeModel: "Airbus A330-300",
    planeRegistration: "C-GFAH",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YUL,
    departureAirport: "YVR",
    arrivalAirport: "YUL",
    originAirportId: 1,
    destinationAirportId: 4,
  },
  {
    id: 54,
    flightNumber: "AC8730",
    airline: "Air Canada",
    date: new Date("2018-06-30"),
    planeModel: "DHC-8-400 Dash 8Q",
    planeRegistration: "C-GGDU",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YUL,
    destinationAirport: airportDatabase.YQB,
    departureAirport: "YUL",
    arrivalAirport: "YQB",
    originAirportId: 4,
    destinationAirportId: 30,
  },
  {
    id: 55,
    flightNumber: "UA1098",
    airline: "United Airlines",
    date: new Date("2018-04-22"),
    planeModel: "Boeing 737-800",
    planeRegistration: "N76529",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.IAH,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "IAH",
    arrivalAirport: "YVR",
    originAirportId: 28,
    destinationAirportId: 1,
  },
  {
    id: 56,
    flightNumber: "AC126",
    airline: "Air Canada",
    date: new Date("2018-04-17"),
    planeModel: "Boeing 777-300 ER",
    planeRegistration: "C-FNNU",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYZ,
    departureAirport: "YVR",
    arrivalAirport: "YYZ",
    originAirportId: 1,
    destinationAirportId: 18,
  },
  {
    id: 57,
    flightNumber: "AC591",
    airline: "Air Canada",
    date: new Date("2018-04-17"),
    planeModel: "Embraer 190",
    planeRegistration: "C-FHNV",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYZ,
    destinationAirport: airportDatabase.IAH,
    departureAirport: "YYZ",
    arrivalAirport: "IAH",
    originAirportId: 18,
    destinationAirportId: 28,
  },
  {
    id: 58,
    flightNumber: "AC103",
    airline: "Air Canada",
    date: new Date("2017-08-20"),
    planeModel: "Boeing 777-300 ER",
    planeRegistration: "C-FNNQ",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYZ,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YYZ",
    arrivalAirport: "YVR",
    originAirportId: 18,
    destinationAirportId: 1,
  },
  {
    id: 59,
    flightNumber: "EI157",
    airline: "Aer Lingus",
    date: new Date("2017-08-19"),
    planeModel: "Airbus A320",
    planeRegistration: "EI-CVB",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.LHR,
    destinationAirport: airportDatabase.DUB,
    departureAirport: "LHR",
    arrivalAirport: "DUB",
    originAirportId: 31,
    destinationAirportId: 32,
  },
  {
    id: 60,
    flightNumber: "EI129",
    airline: "Aer Lingus",
    date: new Date("2017-08-19"),
    planeModel: "Airbus A330-300",
    planeRegistration: "EI-FNH",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.DUB,
    destinationAirport: airportDatabase.YYZ,
    departureAirport: "DUB",
    arrivalAirport: "YYZ",
    originAirportId: 32,
    destinationAirportId: 18,
  },
  {
    id: 61,
    flightNumber: "EI262",
    airline: "Aer Lingus",
    date: new Date("2017-08-11"),
    planeModel: "Airbus A320",
    planeRegistration: "EI-FNJ",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.DUB,
    destinationAirport: airportDatabase.BHX,
    departureAirport: "DUB",
    arrivalAirport: "BHX",
    originAirportId: 32,
    destinationAirportId: 33,
  },
  {
    id: 62,
    flightNumber: "EI128",
    airline: "Aer Lingus",
    date: new Date("2017-08-10"),
    planeModel: "Airbus A330-200",
    planeRegistration: "EI-EWR",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYZ,
    destinationAirport: airportDatabase.DUB,
    departureAirport: "YYZ",
    arrivalAirport: "DUB",
    originAirportId: 18,
    destinationAirportId: 32,
  },
  {
    id: 63,
    flightNumber: "AC122",
    airline: "Air Canada",
    date: new Date("2017-08-09"),
    planeModel: "Airbus A320",
    planeRegistration: "C-FDQV",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYZ,
    departureAirport: "YVR",
    arrivalAirport: "YYZ",
    originAirportId: 1,
    destinationAirportId: 18,
  },
  {
    id: 64,
    flightNumber: "AC549",
    airline: "Air Canada",
    date: new Date("2017-03-24"),
    planeModel: "Boeing 787-9",
    planeRegistration: "C-FRSI",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.EWR,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "EWR",
    arrivalAirport: "YVR",
    originAirportId: 34,
    destinationAirportId: 1,
  },
  {
    id: 65,
    flightNumber: "UA665",
    airline: "United Airlines",
    date: new Date("2017-03-23"),
    planeModel: "Boeing 737-800",
    planeRegistration: "N78511",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.IAH,
    destinationAirport: airportDatabase.EWR,
    departureAirport: "IAH",
    arrivalAirport: "EWR",
    originAirportId: 28,
    destinationAirportId: 34,
  },
  {
    id: 66,
    flightNumber: "UA855",
    airline: "United Airlines",
    date: new Date("2017-03-23"),
    planeModel: "Boeing 767-300",
    planeRegistration: "N662UA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.LIM,
    destinationAirport: airportDatabase.IAH,
    departureAirport: "LIM",
    arrivalAirport: "IAH",
    originAirportId: 35,
    destinationAirportId: 28,
  },
  {
    id: 67,
    flightNumber: "AV808",
    airline: "Avianca",
    date: new Date("2017-03-22"),
    planeModel: "Airbus A320",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.CUZ,
    destinationAirport: airportDatabase.LIM,
    departureAirport: "CUZ",
    arrivalAirport: "LIM",
    originAirportId: 36,
    destinationAirportId: 35,
  },
  {
    id: 68,
    flightNumber: "AV808",
    airline: "Avianca",
    date: new Date("2017-03-19"),
    planeModel: "Airbus A320",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.PEM,
    destinationAirport: airportDatabase.CUZ,
    departureAirport: "PEM",
    arrivalAirport: "CUZ",
    originAirportId: 37,
    destinationAirportId: 36,
  },
  {
    id: 69,
    flightNumber: "AV807",
    airline: "Avianca",
    date: new Date("2017-03-14"),
    planeModel: "Airbus A320",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.LIM,
    destinationAirport: airportDatabase.CUZ,
    departureAirport: "LIM",
    arrivalAirport: "CUZ",
    originAirportId: 35,
    destinationAirportId: 36,
  },
  {
    id: 70,
    flightNumber: "AV809",
    airline: "Avianca",
    date: new Date("2017-03-14"),
    planeModel: "Airbus A320",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.CUZ,
    destinationAirport: airportDatabase.PEM,
    departureAirport: "CUZ",
    arrivalAirport: "PEM",
    originAirportId: 36,
    destinationAirportId: 37,
  },
  {
    id: 71,
    flightNumber: "UA2023",
    airline: "United Airlines",
    date: new Date("2017-03-13"),
    planeModel: "Boeing 737-800",
    planeRegistration: "N24212",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.IAH,
    departureAirport: "YVR",
    arrivalAirport: "IAH",
    originAirportId: 1,
    destinationAirportId: 28,
  },
  {
    id: 72,
    flightNumber: "UA854",
    airline: "United Airlines",
    date: new Date("2017-03-13"),
    planeModel: "Boeing 767-300",
    planeRegistration: "N666UA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.IAH,
    destinationAirport: airportDatabase.LIM,
    departureAirport: "IAH",
    arrivalAirport: "LIM",
    originAirportId: 28,
    destinationAirportId: 35,
  },
  {
    id: 73,
    flightNumber: "LH492",
    airline: "Lufthansa",
    date: new Date("2017-01-05"),
    planeModel: "Boeing 747-400",
    planeRegistration: "DA-BVS",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.FRA,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "FRA",
    arrivalAirport: "YVR",
    originAirportId: 6,
    destinationAirportId: 1,
  },
  {
    id: 74,
    flightNumber: "EW1463",
    airline: "Air Canada",
    date: new Date("2016-12-15"),
    planeModel: "Airbus A320",
    planeRegistration: "D-AEWF",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.LHR,
    destinationAirport: airportDatabase.DUS,
    departureAirport: "LHR",
    arrivalAirport: "DUS",
    originAirportId: 31,
    destinationAirportId: 38,
  },
  {
    id: 75,
    flightNumber: "AC854",
    airline: "Air Canada",
    date: new Date("2016-12-15"),
    planeModel: "Boeing 777-300 ER",
    planeRegistration: "C-FNNW",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.LHR,
    departureAirport: "YVR",
    arrivalAirport: "LHR",
    originAirportId: 1,
    destinationAirportId: 31,
  },
  {
    id: 76,
    flightNumber: "UA784",
    airline: "United Airlines",
    date: new Date("2014-07-02"),
    planeModel: "Airbus A319",
    planeRegistration: "N836UA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.SFO,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "SFO",
    arrivalAirport: "YVR",
    originAirportId: 27,
    destinationAirportId: 1,
  },
  {
    id: 77,
    flightNumber: "UA1724",
    airline: "United Airlines",
    date: new Date("2014-07-02"),
    planeModel: "Boeing 757-300",
    planeRegistration: "N57870",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.KOA,
    destinationAirport: airportDatabase.SFO,
    departureAirport: "KOA",
    arrivalAirport: "SFO",
    originAirportId: 39,
    destinationAirportId: 27,
  },
  {
    id: 78,
    flightNumber: "AA2369",
    airline: "American Airlines",
    date: new Date("2014-01-06"),
    planeModel: "Boeing 737-800",
    planeRegistration: "N918NN",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.DFW,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "DFW",
    arrivalAirport: "YVR",
    originAirportId: 40,
    destinationAirportId: 1,
  },
  {
    id: 79,
    flightNumber: "AA51",
    airline: "United Airlines",
    date: new Date("2014-01-06"),
    planeModel: "Boeing 777-300 ER",
    planeRegistration: "N720AN",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.LHR,
    destinationAirport: airportDatabase.DFW,
    departureAirport: "LHR",
    arrivalAirport: "DFW",
    originAirportId: 31,
    destinationAirportId: 40,
  },
  {
    id: 80,
    flightNumber: "BA935",
    airline: "British Airways",
    date: new Date("2014-01-06"),
    planeModel: undefined,
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.DUS,
    destinationAirport: airportDatabase.LHR,
    departureAirport: "DUS",
    arrivalAirport: "LHR",
    originAirportId: 38,
    destinationAirportId: 31,
  },
  {
    id: 81,
    flightNumber: "AA242",
    airline: "American Airlines",
    date: new Date("2013-12-12"),
    planeModel: "Boeing 767-300",
    planeRegistration: "N355AA",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.ORD,
    destinationAirport: airportDatabase.DUS,
    departureAirport: "ORD",
    arrivalAirport: "DUS",
    originAirportId: 25,
    destinationAirportId: 38,
  },
  {
    id: 82,
    flightNumber: "AA1236",
    airline: "American Airlines",
    date: new Date("2013-12-12"),
    planeModel: "Boeing 737-800",
    planeRegistration: "N933NN",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.SEA,
    destinationAirport: airportDatabase.ORD,
    departureAirport: "SEA",
    arrivalAirport: "ORD",
    originAirportId: 10,
    destinationAirportId: 25,
  },
  {
    id: 83,
    flightNumber: "AS2227",
    airline: "Alaska Airlines",
    date: new Date("2013-12-12"),
    planeModel: "DHC-8-400 Dash 8Q",
    planeRegistration: "N409QX",
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.SEA,
    departureAirport: "YVR",
    arrivalAirport: "SEA",
    originAirportId: 1,
    destinationAirportId: 10,
  },
  {
    id: 84,
    flightNumber: "KL681",
    airline: "KLM",
    date: new Date("2012-11-06"),
    planeModel: "Airbus A330",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "AMS",
    arrivalAirport: "YVR",
    originAirportId: 9,
    destinationAirportId: 1,
  },
  {
    id: 85,
    flightNumber: "KL682",
    airline: "KLM",
    date: new Date("2012-10-16"),
    planeModel: "Boeing 777",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "YVR",
    arrivalAirport: "AMS",
    originAirportId: 1,
    destinationAirportId: 9,
  },
  {
    id: 86,
    flightNumber: "LH492",
    airline: "Lufthansa",
    date: new Date("2012-01-09"),
    planeModel: "Airbus A340-300",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.FRA,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "FRA",
    arrivalAirport: "YVR",
    originAirportId: 6,
    destinationAirportId: 1,
  },
  {
    id: 87,
    flightNumber: "LH493",
    airline: "Lufthansa",
    date: new Date("2011-12-14"),
    planeModel: "Airbus A340-300",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.FRA,
    departureAirport: "YVR",
    arrivalAirport: "FRA",
    originAirportId: 1,
    destinationAirportId: 6,
  },
  {
    id: 88,
    flightNumber: "AC151",
    airline: "Air Canada",
    date: new Date("2011-08-20"),
    planeModel: "Airbus A321",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YYZ,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "YYZ",
    arrivalAirport: "YVR",
    originAirportId: 18,
    destinationAirportId: 1,
  },
  {
    id: 89,
    flightNumber: "AC136",
    airline: "Air Canada",
    date: new Date("2011-08-14"),
    planeModel: "Boeing 767-300",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.YYZ,
    departureAirport: "YVR",
    arrivalAirport: "YYZ",
    originAirportId: 1,
    destinationAirportId: 18,
  },
  {
    id: 90,
    flightNumber: "KL1858",
    airline: "KLM",
    date: new Date("2011-01-04"),
    planeModel: "Fokker 70",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.DUS,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "DUS",
    arrivalAirport: "AMS",
    originAirportId: 38,
    destinationAirportId: 9,
  },
  {
    id: 91,
    flightNumber: "KL681",
    airline: "KLM",
    date: new Date("2011-01-04"),
    planeModel: "McDonnell Douglas MD-11",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.YVR,
    departureAirport: "AMS",
    arrivalAirport: "YVR",
    originAirportId: 9,
    destinationAirportId: 1,
  },
  {
    id: 92,
    flightNumber: "KL1861",
    airline: "KLM",
    date: new Date("2010-12-15"),
    planeModel: "Fokker 70",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.AMS,
    destinationAirport: airportDatabase.DUS,
    departureAirport: "AMS",
    arrivalAirport: "DUS",
    originAirportId: 9,
    destinationAirportId: 38,
  },
  {
    id: 93,
    flightNumber: "KL682",
    airline: "KLM",
    date: new Date("2010-12-14"),
    planeModel: "McDonnell Douglas MD-11",
    planeRegistration: undefined,
    userId: 1,
    user: { id: "1", username: "testuser", nickname: "Test User" },
    originAirport: airportDatabase.YVR,
    destinationAirport: airportDatabase.AMS,
    departureAirport: "YVR",
    arrivalAirport: "AMS",
    originAirportId: 1,
    destinationAirportId: 9,
  },
];

export const mockFlightLog = {
  message: "Mock flight data",
  total: mockFlights.length,
  items: mockFlights,
};
